// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muinzrgfkdwugqwistvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11aW56cmdma2R3dWdxd2lzdHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzY4OTksImV4cCI6MjA2OTk1Mjg5OX0.IdYFtrfkcqTDAWNWAT2lmpFXlznRSpQe11a1tHPD6SY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});